### ISSUE TITLE
Issue with owner group from client.keys file after upgrade to 4.3.0

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1025]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0-1 | Manager | Upgrade | All |

Errors are found in the Checkfiles.py after upgrading from versions 3.5.x, 3.6.x and 3.7.x, the script detects a file with a gid that does not exist, example:

OS: Centos 8
Wazuh gid after upgrade: 994
![image](https://user-images.githubusercontent.com/64099752/143616673-11e826b5-c766-42da-ace5-58fad10876b5.png)

Jenkins Jobs:
3.5.0: https://devel.ci.wazuh.info/job/Test-Upgrade-cbordon/1222/console
3.6.1: https://devel.ci.wazuh.info/job/Test-Upgrade-cbordon/1223/console
3.7.2: https://devel.ci.wazuh.info/job/Test-Upgrade-cbordon/1224/console

**Comment by c-bordon** [comment]
I did some tests and I was able to detect that the script that performs the change of permissions works correctly, that is, after the update all the permissions are changed.

I did an upgrade test, and I was able to validate that after the check_files the permission changes; I still don't understand why.

Permissions after upgrade but before checkfiles:

```
[root@ip-172-31-28-229 ~]# ls -la /var/ossec/etc/
total 104
drwxrwx--- 1 wazuh wazuh  4096 Dec 14 16:09 .
drwxr-x--- 1 root  wazuh  4096 Dec 14 16:09 ..
-rw-r----- 1 root  wazuh   113 Dec 14 16:07 client.keys
-rw-r----- 1 root  wazuh     0 Dec 14 15:31 client.keys.rpmnew
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 decoders
-rw-r----- 1 root  wazuh 13662 Dec 14 15:31 internal_options.conf
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 lists
-rw-r----- 1 root  wazuh   386 Dec 14 16:08 local_internal_options.conf
-rw-r----- 1 root  wazuh   118 Dec 14 15:31 localtime
lrwxrwxrwx 1 root  root     20 Nov 10  2020 ossec-init.conf -> /etc/ossec-init.conf
-rw-r----- 1 root  wazuh  8591 Dec 14 16:08 ossec.conf
-rw-rw---- 1 root  wazuh  9835 Dec 14 15:31 ossec.conf.rpmnew
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 rootcheck
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 rules
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 shared
-rw-r----- 1 root  root   1196 Nov 10  2020 sslmanager.cert
-rw-r----- 1 root  root   1708 Nov 10  2020 sslmanager.key

```

Permissions after the checkfiles:

```
[root@ip-172-31-28-229 ~]# ls -la /var/ossec/etc/           
total 104
drwxrwx--- 1 wazuh wazuh  4096 Dec 14 16:09 .
drwxr-x--- 1 root  wazuh  4096 Dec 14 16:09 ..
-rw-r----- 1 root    995   113 Dec 14 16:09 client.keys
-rw-r----- 1 root  wazuh     0 Dec 14 15:31 client.keys.rpmnew
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 decoders
-rw-r----- 1 root  wazuh 13662 Dec 14 15:31 internal_options.conf
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 lists
-rw-r----- 1 root  wazuh   386 Dec 14 16:08 local_internal_options.conf
-rw-r----- 1 root  wazuh   127 Oct 26  2020 localtime
-rw-r----- 1 root  wazuh  8591 Dec 14 16:08 ossec.conf
-rw-rw---- 1 root  wazuh  9835 Dec 14 15:31 ossec.conf.rpmnew
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 rootcheck
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 rules
drwxrwx--- 1 root  wazuh  4096 Dec 14 16:09 shared
-rw-r----- 1 root  root   1196 Nov 10  2020 sslmanager.cert
-rw-r----- 1 root  root   1708 Nov 10  2020 sslmanager.key

```

When I upgraded by hand, the permissions did not change:

```
[root@4baac112d3e7 ~]# ls -la /var/ossec/etc/
total 100
drwxrwx--- 1 wazuh wazuh  4096 Nov 15 19:22 .
drwxr-x--- 1 root  wazuh  4096 Nov 15 19:22 ..
-rw-r----- 1 root  wazuh     0 Nov 12 19:50 client.keys
drwxrwx--- 1 root  wazuh  4096 Nov 15 19:22 decoders
-rw-r----- 1 root  wazuh 13348 Nov 12 19:50 internal_options.conf
drwxrwx--- 1 root  wazuh  4096 Dec 14 14:20 lists
-rw-r----- 1 root  wazuh   320 Nov 12 19:50 local_internal_options.conf
-rw-r----- 1 root  wazuh   127 Jan 26  2021 localtime
-rw-rw---- 1 root  wazuh  9522 Nov 15 19:22 ossec.conf
drwxrwx--- 1 root  wazuh  4096 Nov 15 19:22 rootcheck
drwxrwx--- 1 root  wazuh  4096 Nov 15 19:22 rules
drwxrwx--- 1 root  wazuh  4096 Dec 14 14:20 shared
-rw-r----- 1 root  root   1196 Nov 15 19:22 sslmanager.cert
-rw-r----- 1 root  root   1704 Nov 15 19:22 sslmanager.key

```
I continue to investigate in which part of the checkfile process this change of permissions can be made

Tested on Centos 8, from Wazuh 3.5.0 to 4.3.0

**Comment by c-bordon** [comment]
I was doing new tests and I was able to verify that the change of owner occurs in the installation process, apparently, it could not be a problem in cicd.
I was able to verify that performing the upgrade manually using yum localinstall or dnf localinstall with the same package, this problem does not occur:

```
[root@centos7 ~]# dnf install ./wazuh-manager-4.3.0-1.x86_64.rpm 

[root@centos7 ~]# ls -la /var/ossec/etc/
total 64
drwxrwx---.  7 wazuh wazuh   267 Dec 15 19:45 .
drwxr-x---. 19 root  wazuh   242 Dec 15 19:45 ..
-rw-r-----.  1 root  wazuh    92 Dec 15 19:45 client.keys
drwxrwx---.  2 root  wazuh    31 Dec 15 19:45 decoders
-rw-r-----.  1 root  wazuh 13662 Nov 24 21:37 internal_options.conf
drwxrwx---.  3 root  wazuh    89 Dec 15 19:45 lists
-rw-r-----.  1 root  wazuh   320 Nov 24 21:37 local_internal_options.conf
-rw-r-----.  1 root  wazuh   118 Apr 30  2020 localtime
-rw-rw----.  1 root  wazuh  9263 Dec 15 19:35 ossec.conf
-rw-rw----.  1 root  wazuh  9835 Nov 24 21:37 ossec.conf.rpmnew
drwxrwx---.  2 root  wazuh  4096 Dec 15 19:45 rootcheck
drwxrwx---.  2 root  wazuh    29 Dec 15 19:45 rules
drwxrwx---.  3 root  wazuh    63 Dec 15 19:45 shared
-rw-r-----.  1 root  root   1176 Dec 15 19:35 sslmanager.cert
-rw-r-----.  1 root  root   1704 Dec 15 19:35 sslmanager.key
```

**Comment by c-bordon** [comment]
I continue doing some local tests, I could get to the point of knowing that the change of permissions occurs in the step:
```
  Cleanup    : wazuh-manager-3.5.0-1.x86_64    
```

I'm doing tests assembling packages, but at the moment I can't correct it yet

**Comment by c-bordon** [comment]
I have a fix that works locally, I made a package with this fix but in Jenkins pipelines, it keeps crashing.
https://devel.ci.wazuh.info/view/Tests/job/Test_upgrade/54547/console

```
15:26:31  STDERR:
15:26:31  
15:26:31  Traceback (most recent call last):
15:26:31    File "./check_files.py", line 459, in <module>
15:26:31      current_items = get_current_items(OSSEC_PATH, ignore_names)
15:26:31    File "./check_files.py", line 310, in get_current_items
15:26:31      c_items[file_path] = get_data(file_path)
15:26:31    File "./check_files.py", line 124, in get_data
15:26:31      group = grp.getgrgid(stat_info.st_gid)[0]
15:26:31  KeyError: 'getgrgid(): gid not found: 107'
15:26:31  
15:26:31  
15:26:31  MSG:
15:26:31  
```

local tests:
```
root@Debian-Buster:~# ls -la /var/ossec/etc/
total 88
drwxrwx---  7 wazuh wazuh  4096 Dec 20 18:17 .
drwxr-x--- 19 root  wazuh  4096 Dec 20 18:17 ..
-rw-r-----  1 wazuh wazuh    99 Dec 20 18:17 client.keys
drwxrwx---  2 root  wazuh  4096 Dec 20 18:17 decoders
-rw-r-----  1 root  wazuh 13662 Dec 20 16:59 internal_options.conf
drwxrwx---  3 root  wazuh  4096 Dec 20 18:11 lists
-rw-r-----  1 root  wazuh   320 Aug  9  2018 local_internal_options.conf
-rw-r-----  1 root  wazuh   127 Jan 27  2021 localtime
-rw-rw----  1 root  wazuh  9077 Dec 20 18:11 ossec.conf
-rw-rw----  1 root  root   9703 Dec 20 18:17 ossec.conf.new
drwxrwx---  2 root  wazuh  4096 Dec 20 18:17 rootcheck
drwxrwx---  2 root  wazuh  4096 Dec 20 18:17 rules
drwxrwx---  3 root  wazuh  4096 Dec 20 18:17 shared
-rw-r-----  1 root  root   1196 Dec 20 18:17 sslmanager.cert
-rw-r-----  1 root  root   1708 Dec 20 18:17 sslmanager.key
```

**Comment by c-bordon** [comment]
I continue investigating because it works locally and not in the executions of Jenkins, I could also verify that the permissions fix generates a problem since the packages_files directory is not deleted:

```
17:49:20  Extra (Not present in the chek-files but they are installed):
17:49:20  /var/ossec/packages_files  [root root 0755 drwxr-xr-x]
17:49:20  /var/ossec/packages_files/agent_config_files  [root root 0755 drwxr-xr-x]
17:49:20  /var/ossec/packages_files/agent_config_files/client.keys  [root root 0640 -rw-r-----]
17:49:20  /var/ossec/packages_files/agent_config_files/wazuh.restart  [root root 0644 -rw-r--r--]
17:49:20  /var/ossec/packages_files/agent_installation_scripts  [root root 0755 drwxr-xr-x]
17:49:20  /var/ossec/packages_files/agent_installation_scripts/add_localfiles.sh  [root root 0755 -rwxr-xr-x]
```

**Comment by c-bordon** [comment]
With the Core team, we were able to validate that the change of permissions occurs when the ossec-authd daemon is restarted or eliminated, at the end of the process, it dumps the information it has in memory in the client.keys, so initially the fix This is correct, it remains to be resolved for the case of containers, where for some reason that I am investigating the ossec-authd process, it does not end, I am reviewing the restart process of the packages.

**Comment by c-bordon** [comment]
I am working on the Debian package, it continues to fail in the installation, at least I could verify that the problem occurs in the generation of the wazuh.restart file.

The validations are not being fulfilled, therefore they are not entering and generating the file, although a couple of them are fulfilled, I am checking because they do not enter:

https://github.com/wazuh/wazuh-packages/blob/9867bbe2f7f6bea7ec681eb0cfc555f5a7c3af8f/debs/SPECS/4.3.0/wazuh-manager/debian/preinst#L27

**Comment by c-bordon** [comment]
Fixed the Issue in the managers in the commit https://github.com/wazuh/wazuh-packages/commit/2e3a116b7d800968601c6dc54ddbd7612d11a803

Jenkins tests:
https://devel.ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1492/console

An error is identified in the debian packages for agents, in the Jenkins tests it can be verified that the packages_files directory is not deleted, this behavior could not be replicated in local tests, with the same package as in jenkins, I am investigating

```
13:55:15  Checking files...
13:55:15  
13:55:15  Extra (Not present in the chek-files but they are installed):
13:55:15  /var/ossec/packages_files  [root root 0755 drwxr-xr-x]
13:55:15  /var/ossec/packages_files/agent_config_files  [root root 0755 drwxr-xr-x]
13:55:15  /var/ossec/packages_files/agent_config_files/client.keys  [root root 0640 -rw-r-----]
13:55:15  /var/ossec/packages_files/agent_installation_scripts  [root root 0755 drwxr-xr-x]
13:55:15  /var/ossec/packages_files/agent_installation_scripts/add_localfiles.sh  [root root 0755 -rwxr-xr-x]
13:55:15  /var/ossec/packages_files/agent_installation_scripts/etc  [root root 0755 drwxr-xr-x]
```

**Comment by c-bordon** [comment]
Apparently, I already have the package with the Fix, I'm waiting for the upgrade tests to finish to validate the correct behavior:

https://devel.ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1496/console
Some errors found:

4.2.5:
https://devel.ci.wazuh.info/job/Test_upgrade/55100/console
```
16:43:54  2021/12/27 19:42:35 wazuh-agentd: ERROR: Duplicate agent name: ip-172-31-72-114.ec2.internal (from manager)
16:43:54  
16:43:54  2021/12/27 19:42:35 wazuh-agentd: ERROR: Unable to add agent (from manager)
```
3.13.3:
https://devel.ci.wazuh.info/job/Test_upgrade/55141/console
```
17:12:04  TASK [Starting ossec-agent service] ********************************************
17:12:04  fatal: [amd64-fedora-31-agent-3_13_3_1]: FAILED! => {
17:12:04      "changed": true,
17:12:04      "cmd": [
17:12:04          "/var/ossec/bin/ossec-control",
17:12:04          "start"
17:12:04      ],
17:12:04      "delta": "0:00:11.091423",
17:12:04      "end": "2021-12-27 20:12:04.474663",
17:12:04      "rc": 1,
17:12:04      "start": "2021-12-27 20:11:53.383240"
17:12:04  }
17:12:04  
17:12:04  STDOUT:
17:12:04  
17:12:04  Starting Wazuh v3.13.3...
17:12:04  Started ossec-execd...
17:12:04  ossec-agentd did not start
17:12:04  
17:12:04  
17:12:04  MSG:
17:12:04  
17:12:04  non-zero return code
17:12:04  
```

3.12.3:
https://devel.ci.wazuh.info/job/Test_upgrade/55154/console
```
api.pid,/var/ossec/tmp,/var/ossec/framework/python', no_show_ignore_list=True, os='linux', target='manager', test='upgrade', version='4.3.0')
17:19:35  Checking files...
17:19:35  
17:19:35  Extra (Not present in the chek-files but they are installed):
17:19:35  /var/ossec/queue/db/global.db-journal  [wazuh wazuh 0640 -rw-r-----]
17:19:35  
17:19:35  
17:19:35  Please, review your files.
```
