### ISSUE TITLE
Generate random passwords in unified unattended

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#1057]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 | Unattended | Install | OS version |

We need to add the functionality so the unified unattended script can automatically randomize the Opendistro passwords, both for All-In-One and for distributed installation,.

**Comment by DFolchA** [comment]
## UPDATE

- Make All In One installation generate random passwords and show them in standard output
- Create a function to generate password file for distributed installation
- Make Distributed installation change the passwords according to the password file
- Work in how to start OD cluster automatically in distributed installation

## TO DO
- Test distributed installation

**Comment by rauldpm** [comment]
### Update report



<details><summary>Error: wazuh-passwords-tool.sh -a -v</summary>

    - This command doesn't update filebeat.yml passwords. Its empty after the process.

  ```
  [root@wazuh-manager wazuh-user]# bash wazuh-passwords-tool.sh -a -v
  12/15/2021 22:34:32 INFO: Generating random passwords
  12/15/2021 22:34:32 INFO: Done
  12/15/2021 22:34:32 INFO: Creating backup...
  Open Distro Security Admin v7
  ERR: Parsing failed.  Reason: Missing argument for option: key
  usage: securityadmin.sh [-arc] [-backup <folder>] [-cacert <file>] [-cd
         <directory>] [-cert <file>] [-cn <clustername>] [-dci] [-dg] [-dra]
         [-ec <cipers>] [-ep <protocols>] [-er <number of replicas>] [-era]
         [-esa] [-f <file>] [-ff] [-h <host>] [-i <indexname>] [-icl] [-key
         <file>] [-keypass <password>] [-ks <file>] [-ksalias <alias>]
         [-kspass <password>] [-kst <type>] [-migrate <folder>] [-mo
         <folder>] [-nhnv] [-noopenssl] [-nrhn] [-p <port>] [-prompt] [-r]
         [-rev] [-rl] [-si] [-sniff] [-t <file-type>] [-ts <file>] [-tsalias
         <alias>] [-tspass <password>] [-tst <type>] [-us <number of
         replicas>] [-vc <version>] [-w]
   -arc,--accept-red-cluster                      Also operate on a red
                                                  cluster. If not specified
                                                  the cluster state has to
                                                  be at least yellow.
   -backup <folder>                               Backup configuration to
                                                  folder
   -cacert <file>                                 Path to trusted cacert
                                                  (PEM format)
   -cd,--configdir <directory>                    Directory for config files
   -cert <file>                                   Path to admin certificate
                                                  in PEM format
   -cn,--clustername <clustername>                Clustername (do not use
                                                  together with -icl)
   -dci,--delete-config-index                     Delete
                                                  '.opendistro_security'
                                                  config index and exit.
   -dg,--diagnose                                 Log diagnostic trace into
                                                  a file
   -dra,--disable-replica-autoexpand              Disable replica auto
                                                  expand and exit
   -ec,--enabled-ciphers <cipers>                 Comma separated list of
                                                  enabled TLS ciphers
   -ep,--enabled-protocols <protocols>            Comma separated list of
                                                  enabled TLS protocols
   -er,--explicit-replicas <number of replicas>   Set explicit number of
                                                  replicas or autoexpand
                                                  expression for
                                                  .opendistro_security index
   -era,--enable-replica-autoexpand               Enable replica auto expand
                                                  and exit
   -esa,--enable-shard-allocation                 Enable all shard
                                                  allocation and exit.
   -f,--file <file>                               file
   -ff,--fail-fast                                fail-fast if something
                                                  goes wrong
   -h,--hostname <host>                           Elasticsearch host
                                                  (default: localhost)
   -i,--index <indexname>                         The index Open Distro
                                                  Security uses to store the
                                                  configuration
   -icl,--ignore-clustername                      Ignore clustername (do not
                                                  use together with -cn)
   -key <file>                                    Path to the key of admin
                                                  certificate
   -keypass <password>                            Password of the key of
                                                  admin certificate
                                                  (optional)
   -ks,--keystore <file>                          Path to keystore
                                                  (JKS/PKCS12 format
   -ksalias,--keystore-alias <alias>              Keystore alias
   -kspass,--keystore-password <password>         Keystore password
   -kst,--keystore-type <type>                    JKS or PKCS12, if not
                                                  given we use the file
                                                  extension to dectect the
                                                  type
   -migrate <folder>                              Migrate and use folder to
                                                  store migrated files
   -mo,--migrate-offline <folder>                 Migrate and use folder to
                                                  store migrated files
   -nhnv,--disable-host-name-verification         Disable hostname
                                                  verification
   -noopenssl,--no-openssl                        Do not use OpenSSL even if
                                                  available (default: use it
                                                  if available)
   -nrhn,--disable-resolve-hostname               Disable DNS lookup of
                                                  hostnames
   -p,--port <port>                               Elasticsearch transport
                                                  port (default: 9300)
   -prompt,--prompt-for-password                  Prompt for password if not
                                                  supplied
   -r,--retrieve                                  retrieve current config
   -rev,--resolve-env-vars                        Resolve/Substitute env
                                                  vars in config with their
                                                  value before uploading
   -rl,--reload                                   Reload the configuration
                                                  on all nodes, flush all
                                                  Open Distro Security
                                                  caches and exit
   -si,--show-info                                Show system and license
                                                  info
   -sniff,--enable-sniffing                       Enable
                                                  client.transport.sniff
   -t,--type <file-type>                          file-type
   -ts,--truststore <file>                        Path to truststore
                                                  (JKS/PKCS12 format)
   -tsalias,--truststore-alias <alias>            Truststore alias
   -tspass,--truststore-password <password>       Truststore password
   -tst,--truststore-type <type>                  JKS or PKCS12, if not
                                                  given we use the file
                                                  extension to dectect the
                                                  type
   -us,--update_settings <number of replicas>     Update the number of Open
                                                  Distro Security index
                                                  replicas, reload
                                                  configuration on all nodes
                                                  and exit
   -vc,--validate-configs <version>               Validate config for
                                                  version 6 or 7 (default 7)
   -w,--whoami                                    Show information about the
                                                  used admin certificate
  12/15/2021 22:34:32 INFO: Backup created
  12/15/2021 22:34:32 INFO: Generating hashes
  12/15/2021 22:34:36 INFO: Hashes generated
  12/15/2021 22:34:36 INFO: Filebeat started
  12/15/2021 22:34:36 INFO: Kibana started
  12/15/2021 22:34:36 INFO: Loading changes...
  cp: cannot stat ‘/usr/share/elasticsearch/backup/*’: No such file or directory
  Open Distro Security Admin v7
  Will connect to localhost:9300 ... done
  ERR: An unexpected IllegalStateException occured: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
  Trace:
  java.lang.IllegalStateException: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
	  at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:722)
	  at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:124)
	  at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:114)
	  at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:139)
	  at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:282)
	  at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin$TransportClientImpl.<init>(OpenDistroSecurityAdmin.java:1007)
	  at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.execute(OpenDistroSecurityAdmin.java:520)
	  at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.main(OpenDistroSecurityAdmin.java:157)
  Caused by: java.lang.reflect.InvocationTargetException
	  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	  at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:713)
	  ... 7 more
  Caused by: ElasticsearchSecurityException[Error while initializing transport SSL layer from PEM: ElasticsearchException[Is a directory: /usr/share/elasticsearch/plugins/opendistro_security/tools/ Expected a file for opendistro_security.ssl.transport.pemcert_filepath]]; nested: ElasticsearchException[Is a directory: /usr/share/elasticsearch/plugins/opendistro_security/tools/ Expected a file for opendistro_security.ssl.transport.pemcert_filepath];
	  at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.initTransportSSLConfig(DefaultOpenDistroSecurityKeyStore.java:409)
	  at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.initSSLConfig(DefaultOpenDistroSecurityKeyStore.java:248)
	  at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.<init>(DefaultOpenDistroSecurityKeyStore.java:169)
	  at com.amazon.opendistroforelasticsearch.security.ssl.OpenDistroSecuritySSLPlugin.<init>(OpenDistroSecuritySSLPlugin.java:217)
	  at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin.<init>(OpenDistroSecurityPlugin.java:246)
	  ... 13 more
  Caused by: ElasticsearchException[Is a directory: /usr/share/elasticsearch/plugins/opendistro_security/tools/ Expected a file for opendistro_security.ssl.transport.pemcert_filepath]
	  at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.checkPath(DefaultOpenDistroSecurityKeyStore.java:943)
	  at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.resolve(DefaultOpenDistroSecurityKeyStore.java:227)
	  at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.initTransportSSLConfig(DefaultOpenDistroSecurityKeyStore.java:386)
	  ... 17 more
  
  
  12/15/2021 22:34:38 INFO: Done
  
  12/15/2021 22:34:38 INFO: The password for admin is NiSlXXvdQ8fqkkTqXOMpeQUEKbGxcXvj
  
  12/15/2021 22:34:38 INFO: The password for kibanaserver is dON25akW151DzckFkFSlFTbCNTYcO32w
  
  12/15/2021 22:34:38 INFO: The password for kibanaro is Cq8Je8I72HWjgAZI7WQWVid1QvzgbkJH
  
  12/15/2021 22:34:38 INFO: The password for logstash is Izvm2wSNauHVy8yGBNNcV4y9dqJmtf3X
  
  12/15/2021 22:34:38 INFO: The password for readall is EOeDlpvkqlkj6GrSkoyuRF2XlYarVe8Q
  
  12/15/2021 22:34:38 INFO: The password for snapshotrestore is cqqmXc248vL1g2VmXuZVYPiQEAcuVoyg
  
  12/15/2021 22:34:38 INFO: The password for wazuh_admin is Lfl3S5xzS7tVCeqQUnMEbgYoyPGWZLYV
  
  12/15/2021 22:34:38 INFO: The password for wazuh_user is UjGNyVbQK0fwxADAzBATuH1Udv1XOOfW
  
  12/15/2021 22:34:38 WARNING: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services.
  
  [root@wazuh-manager wazuh-user]#
  ```

</details>

**Comment by rauldpm** [comment]
### Update report

- FIxed securityadmin.sh calls. Parameter paths were malformed
- Fixed password file validation. Added `-` character due to AMI instance id.
- Fixed elasticsearch install variable. The installer package was not detected correctly due to $ at the end of the command

**Comment by DFolchA** [comment]
Merge latest changes from main branch and add some fixes.

**Test log**
```
[root@centos7 unattended_scripts]# ./wazuh_install.sh -a -l -d -o
28/12/2021 16:28:32 INFO: Cleaning the installation.
28/12/2021 16:28:32 WARNING: Removing the Wazuh manager.
28/12/2021 16:28:46 WARNING: Removing Elasticsearch.
28/12/2021 16:28:49 WARNING: Removing Filebeat.
28/12/2021 16:28:49 WARNING: Removing Kibana.
28/12/2021 16:28:52 INFO: Installation cleaned. Check the /var/log/wazuh-password-tool.sh file to learn more about the issue.
28/12/2021 16:28:52 INFO: Starting all necessary utility installation.
28/12/2021 16:28:53 INFO: All necessary utility installation finished.
28/12/2021 16:28:53 INFO: Adding the Wazuh repository.
28/12/2021 16:28:53 INFO: Wazuh repository added.
12/28/2021 16:28:54 INFO: Creating the Elasticsearch certificates.
12/28/2021 16:28:54 INFO: Creating Wazuh server certificates.
12/28/2021 16:28:54 INFO: Creating Kibana certificate.
12/28/2021 16:28:54 INFO: Certificates creation finished. They can be found in /home/vagrant/wazuh-packages/unattended_scripts/certs.
12/28/2021 16:28:54 INFO: Generating random passwords
12/28/2021 16:28:54 INFO: Done
28/12/2021 16:28:54 INFO: Check recommended minimum hardware requirements for AIO done.
28/12/2021 16:28:54 INFO: Starting the installation.
28/12/2021 16:28:54 INFO: Starting Open Distro for Elasticsearch installation.
28/12/2021 16:29:48 INFO: Open Distro for Elasticsearch installation finished.
28/12/2021 16:29:51 INFO: Elasticsearch post-install configuration finished.
28/12/2021 16:29:51 INFO: Starting service elasticsearch.
28/12/2021 16:29:59 INFO: Elasticsearch service started.
28/12/2021 16:29:59 INFO: Starting Elasticsearch cluster.
28/12/2021 16:30:08 INFO: Elasticsearch cluster started.
28/12/2021 16:30:08 INFO: Starting the Wazuh manager installation.
28/12/2021 16:31:11 INFO: Wazuh manager installation finished.
28/12/2021 16:31:11 INFO: Starting service wazuh-manager.
28/12/2021 16:31:20 INFO: Wazuh-manager service started.
28/12/2021 16:31:20 INFO: Starting filebeat installation.
28/12/2021 16:31:25 INFO: Filebeat installation finished.
28/12/2021 16:31:27 INFO: Filebeat post-install configuration finished.
28/12/2021 16:31:27 INFO: Starting service filebeat.
28/12/2021 16:31:27 INFO: Filebeat service started.
28/12/2021 16:31:27 INFO: Starting Kibana installation.
28/12/2021 16:32:25 INFO: Kibana installation finished.
28/12/2021 16:32:25 INFO: Starting Wazuh Kibana plugin installation.
28/12/2021 16:32:56 INFO: Wazuh Kibana plugin installation finished.
28/12/2021 16:32:56 INFO: Kibana certificate setup finished.
28/12/2021 16:32:57 INFO: Kibana post-install configuration finished.
28/12/2021 16:32:57 INFO: Starting service kibana.
28/12/2021 16:32:58 INFO: Kibana service started.
12/28/2021 16:33:00 INFO: Creating backup...
12/28/2021 16:33:04 INFO: Backup created
12/28/2021 16:33:04 INFO: Generating hashes
12/28/2021 16:33:08 INFO: Hashes generated
12/28/2021 16:33:09 INFO: Filebeat started
12/28/2021 16:33:09 INFO: Kibana started
12/28/2021 16:33:09 INFO: Loading changes...
12/28/2021 16:33:13 INFO: Done

12/28/2021 16:33:13 INFO: The password for admin is 8gQa2SA3PSTzyKZtbGavPTPril9mVuIB

12/28/2021 16:33:13 INFO: The password for wazuh is C5ZhEUZ7O5fCrHgNBV2dLcDlrxysl89C

12/28/2021 16:33:13 INFO: The password for kibanaserver is Al5JRfLbAZeQvRVFVIuTKg7fO3cIokcX

12/28/2021 16:33:13 INFO: The password for kibanaro is VpOEqNNjRycbYxN4LLTynEaiaaRfO2lH

12/28/2021 16:33:13 INFO: The password for logstash is DOgSebXqQ54xk3pEENok9KiqmWKkZu0K

12/28/2021 16:33:13 INFO: The password for readall is fcDzZL3GhtgIUCOeElR0tyZDwkTxplOk

12/28/2021 16:33:13 INFO: The password for snapshotrestore is 7MzM2mfbVm5m6nCi8pNydBep0nTn7sJx

12/28/2021 16:33:13 INFO: The password for wazuh_admin is rP5IWBuSdKcvsAluLde2mqWnsozThCde

12/28/2021 16:33:13 INFO: The password for wazuh_user is cTQ4N86KxndRtFwUDARvxVdM0hBfzzJU

12/28/2021 16:33:13 WARNING: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services.

28/12/2021 16:33:13 INFO: Starting Kibana (this may take a while).
28/12/2021 16:33:23 INFO: Kibana started.
28/12/2021 16:33:23 INFO: You can access the web interface https://<kibana-host-ip>. The credentials are admin:8gQa2SA3PSTzyKZtbGavPTPril9mVuIB
28/12/2021 16:33:23 INFO: Setting the Wazuh repository to production.
28/12/2021 16:33:23 INFO: The Wazuh repository set to production.
28/12/2021 16:33:23 INFO: Installation Finished.
```

**Comment by DFolchA** [comment]
## Distributed installation

### Elasticsearch
```
root@elastic1:/home/vagrant/repo# ./wazuh_install.sh  -e elastic1 -l -d -i -o
30/12/2021 12:56:43 WARNING: Removing Elasticsearch.
30/12/2021 12:56:48 INFO: Starting all necessary utility installation.
30/12/2021 12:56:50 INFO: All necessary utility installation finished.
30/12/2021 12:56:50 INFO: Adding the Wazuh repository.
30/12/2021 12:56:53 INFO: Wazuh repository added.
30/12/2021 12:56:53 WARNING: Health-check ignored for Elasticsearch.
30/12/2021 12:56:53 INFO: Starting Open Distro for Elasticsearch installation.
30/12/2021 12:59:58 INFO: Open Distro for Elasticsearch installation finished.
30/12/2021 12:59:58 INFO: Configuring Elasticsearch.
30/12/2021 13:00:04 INFO: Starting service elasticsearch.
30/12/2021 13:00:21 INFO: Elasticsearch service started.
30/12/2021 13:00:21 INFO: Starting Elasticsearch cluster.
30/12/2021 13:00:33 INFO: Elasticsearch cluster started.
30/12/2021 13:00:33 INFO: Setting passwords.
12/30/2021 13:00:33 INFO: Creating backup...
12/30/2021 13:00:40 INFO: Backup created
12/30/2021 13:00:40 INFO: Generating hashes
12/30/2021 13:00:47 INFO: Hashes generated
12/30/2021 13:00:47 INFO: Loading changes...
12/30/2021 13:00:54 INFO: Done

12/30/2021 13:00:54 INFO: The password for admin is ZjZsRw0BbB1VrbFmdC0bExrA7wrn2TLu

12/30/2021 13:00:54 INFO: The password for kibanaserver is o8aqQBVKmYOv9MzzRorAjfK0giQC4red

12/30/2021 13:00:54 INFO: The password for kibanaro is A43VWzKW4BBLFLxKonxVDRruXLXXWjsX

12/30/2021 13:00:54 INFO: The password for logstash is JBstaZfa9UMYv6t4Uf4nqCwZGZPaxtt0

12/30/2021 13:00:54 INFO: The password for readall is ABeuk2yGjujNMPp35kwLchSQNmgnhYQ3

12/30/2021 13:00:54 INFO: The password for snapshotrestore is 4A1dsmjFLOyfIK8jokGbwIKgku6JCsvX

12/30/2021 13:00:54 INFO: The password for wazuh_admin is IpvZ2kjYnaEILXGMF51duQKvYK0Ti7sS

12/30/2021 13:00:54 INFO: The password for wazuh_user is QAz7ZgSjFtb5m5ddNl3uwd4TwsfDIYCO

12/30/2021 13:00:54 WARNING: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services.

30/12/2021 13:00:54 INFO: Passwords set.
30/12/2021 13:00:54 INFO: Setting the Wazuh repository to production.
30/12/2021 13:00:54 INFO: The Wazuh repository set to production.
30/12/2021 13:00:54 INFO: Installation Finished.

root@elastic1:/home/vagrant/repo# curl -XGET https://172.16.1.39:9200/ -uadmin:ZjZsRw0BbB1VrbFmdC0bExrA7wrn2TLu -k
{
  "name" : "elastic1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "mZjqv9NdSYiUgbgjTBIkSQ",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "deb",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

```

### Wazuh Manager + Filebeat
```
root@manager1:/home/vagrant/repo# ./wazuh_install.sh -w manager1 -l -i -d -o
30/12/2021 11:55:16 WARNING: Removing the Wazuh manager.
30/12/2021 11:55:24 WARNING: Removing Filebeat.
30/12/2021 11:55:25 INFO: Starting all necessary utility installation.
30/12/2021 11:55:27 INFO: All necessary utility installation finished.
30/12/2021 11:55:27 INFO: Adding the Wazuh repository.
30/12/2021 11:55:30 INFO: Wazuh repository added.
30/12/2021 11:55:30 WARNING: Health-check ignored for Wazuh manager.
30/12/2021 11:55:30 INFO: Starting the Wazuh manager installation.
30/12/2021 11:55:58 INFO: Wazuh manager installation finished.
30/12/2021 11:55:58 INFO: Starting service wazuh-manager.
30/12/2021 11:56:14 INFO: Wazuh-manager service started.
30/12/2021 11:56:14 INFO: Starting filebeat installation.
30/12/2021 11:56:20 INFO: Filebeat installation finished.
30/12/2021 11:56:22 INFO: Filebeat post-install configuration finished.
30/12/2021 11:56:22 INFO: Setting passwords.
12/30/2021 11:56:22 INFO: Filebeat started
30/12/2021 11:56:23 INFO: Passwords set.
30/12/2021 11:56:23 INFO: Starting service filebeat.
30/12/2021 11:56:24 INFO: Filebeat service started.
30/12/2021 11:56:24 INFO: Setting the Wazuh repository to production.
30/12/2021 11:56:24 INFO: The Wazuh repository set to production.
30/12/2021 11:56:24 INFO: Installation Finished.

root@manager1:/home/vagrant/repo# cat /etc/filebeat/filebeat.yml |grep password
  password: ZjZsRw0BbB1VrbFmdC0bExrA7wrn2TLu

```

### Kibana
```
root@kibana1:/home/vagrant/repo# ./wazuh_install.sh  -k kibana1 -l -d -i -o
30/12/2021 13:05:50 WARNING: Removing Kibana.
30/12/2021 13:05:53 INFO: Starting all necessary utility installation.
30/12/2021 13:05:55 INFO: All necessary utility installation finished.
30/12/2021 13:05:55 INFO: Adding the Wazuh repository.
30/12/2021 13:05:58 INFO: Wazuh repository added.
30/12/2021 13:05:58 WARNING: Health-check ignored for Kibana.
30/12/2021 13:05:58 INFO: Starting Kibana installation.
30/12/2021 13:06:17 INFO: Kibana installation finished.
30/12/2021 13:06:29 INFO: Wazuh Kibana plugin installed.
30/12/2021 13:06:31 INFO: Kibana certificate setup finished.
30/12/2021 13:06:31 INFO: Setting passwords.
12/30/2021 13:06:31 INFO: Kibana started
30/12/2021 13:06:31 INFO: Passwords set.
30/12/2021 13:06:31 INFO: Starting service kibana.
30/12/2021 13:06:33 INFO: Kibana service started.
30/12/2021 13:06:33 INFO: Starting Kibana (this may take a while).
30/12/2021 13:06:43 INFO: Kibana started.
30/12/2021 13:06:43 INFO: You can access the web interface https://172.16.1.69. The credentials are admin:ZjZsRw0BbB1VrbFmdC0bExrA7wrn2TLu
30/12/2021 13:06:43 INFO: Setting the Wazuh repository to production.
30/12/2021 13:06:43 INFO: The Wazuh repository set to production.
30/12/2021 13:06:43 INFO: Installation Finished.

root@kibana1:/home/vagrant/repo# cat /usr/share/kibana/data/wazuh/config/wazuh.yml | grep "url: https:"
     url: https://172.16.1.19

root@kibana1:/home/vagrant/repo# cat /etc/kibana/kibana.yml |grep pass
elasticsearch.password: o8aqQBVKmYOv9MzzRorAjfK0giQC4red

root@kibana1:/home/vagrant/repo# curl -XGET https://172.16.1.69/status -I -uadmin:ZjZsRw0BbB1VrbFmdC0bExrA7wrn2TLu -k
HTTP/1.1 200 OK
content-security-policy: script-src 'unsafe-eval' 'self'; worker-src blob: 'self'; style-src 'unsafe-inline' 'self'
kbn-name: kibana1
x-frame-options: sameorigin
content-type: text/html; charset=utf-8
cache-control: private, no-cache, no-store, must-revalidate
set-cookie: security_authentication=Fe26.2**4f0c6c48f38a1288ffe044834489bfc041edbb9fbd879c697c91fc4d21310bd1*n_6DnaXuD39Kh8dI3fdrKA*_Kt2CVq-CdHb_Y1-lgvKg35v9fGMHmtIjk0w-vGEZw1BykXzPXC07JMPMYAOA6k7A3sRNjkEduuJIaX3q1CzrQqecjNhw9h7HprF8IJJ8gsRWvGgxP2cqrHjkN2DNVlToUR22BsHpe0r-ZKQGkjTNGU4xkYT5StOt-bDuAebxYylzjN4ZT7FwNxmeIBhjwNdwtek6tVYaN7ogDUFIQsT12zcoeGlZixp7mODE2GXBlg**c463577341bb01194efae803deeafcd1fdfaa57b311686c7d5b45d0a34bace2a*BdtBBZJq73xsRSW3M2lbV3iF8MlobYxoIxz3JogeEN4; HttpOnly; Path=/
content-length: 93271
vary: accept-encoding
accept-ranges: bytes
Date: Thu, 30 Dec 2021 13:09:30 GMT
Connection: keep-alive
```
