### ISSUE TITLE
Error installing solaris 11 sparc 4.2.5 after removing 4.3.0

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1220]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 | Agent | Install | Solaris11 SPARC |

Hello team,

When testing the Solaris 11 SPARC package, I have seen that when uninstalling version 4.3.0, the wazuh user is not removed and when installing version 4.2.5 the following error occurs:

```
root@sossp534:~# pkg uninstall wazuh-agent
            Packages to remove:  1
            Services to change:  1
       Create boot environment: No
Create backup boot environment: No

PHASE                                          ITEMS
Removing old actions                         187/187
Updating package state database                 Done 
Updating package cache                           1/1 
Updating image state                            Done 
Creating fast lookup database                   Done 
Updating package cache                           2/2 

The following unexpected or editable files and directories were
salvaged while executing the requested package operation; they
have been moved to the displayed location in the image:

  ar/ossec/etc/ossec.conf -> /var/pkg/lost+found/var/ossec/etc/ossec.conf-20220128T195344Z
  ar/ossec/etc/client.keys -> /var/pkg/lost+found/var/ossec/etc/client.keys-20220128T195344Z
  ar/ossec/var/run -> /var/pkg/lost+found/var/ossec/var/run-20220128T195344Z
  ar/ossec/queue/syscollector/db -> /var/pkg/lost+found/var/ossec/queue/syscollector/db-20220128T195344Z
  ar/ossec/queue/sockets -> /var/pkg/lost+found/var/ossec/queue/sockets-20220128T195344Z
  ar/ossec/queue/rids -> /var/pkg/lost+found/var/ossec/queue/rids-20220128T195344Z
  ar/ossec/queue/logcollector -> /var/pkg/lost+found/var/ossec/queue/logcollector-20220128T195344Z
  ar/ossec/queue/fim/db -> /var/pkg/lost+found/var/ossec/queue/fim/db-20220128T195344Z
  ar/ossec/queue/alerts -> /var/pkg/lost+found/var/ossec/queue/alerts-20220128T195344Z
  ar/ossec/etc/shared -> /var/pkg/lost+found/var/ossec/etc/shared-20220128T195344Z
root@sossp534:~# rm -rf /var/pkg/lost+found/var/ossec/
root@sossp534:~# clear

root@sossp534:~# curl -so wazuh-agent_v4.2.5-sol11-sparc.p5p https://packages-dev.wazuh.com/pre-release/solaris/sparc/11/wazuh-agent_v4.2.5-sol11-sparc.p5p
root@sossp534:~# pkg install -g wazuh-agent_v4.2.5-sol11-sparc.p5p wazuh-agent
           Packages to install:  1
            Services to change:  1
       Create boot environment: No
Create backup boot environment: No

DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                1/1         86/86      5.4/5.4 33.8M/s

PHASE                                          ITEMS
Installing new actions                         1/131Action install failed for 'ossec' (pkg://wazuh/wazuh-agent):
  KeyError: 'gid'

The Boot Environment solaris failed to be updated. A snapshot was taken before the failed attempt and is mounted here /tmp/tmpD5VXiA. Use 'beadm unmount solaris-1' and then 'beadm activate solaris-1' if you wish to boot to this BE.
pkg: An unexpected error happened during install: 'gid'
Traceback (most recent call last):
  File "/usr/bin/pkg", line 6254, in handle_errors
    __ret = func(*args, **kwargs)
  File "/usr/bin/pkg", line 6240, in main_func
    pargs=pargs, **opts)
  File "/usr/bin/pkg", line 1985, in install
    update_index=update_index)
  File "/usr/bin/pkg", line 1758, in __api_op
    ret_code = __api_execute_plan(_op, _api_inst)
  File "/usr/bin/pkg", line 1326, in __api_execute_plan
    api_inst.execute_plan()
  File "/usr/lib/python2.7/vendor-packages/pkg/client/api.py", line 2816, in execute_plan
    self._img.imageplan.execute()
  File "/usr/lib/python2.7/vendor-packages/pkg/client/imageplan.py", line 4593, in execute
    p.execute_install(src, dest)
  File "/usr/lib/python2.7/vendor-packages/pkg/client/pkgplan.py", line 563, in execute_install
    dest.install(self, src)
  File "/usr/lib/python2.7/vendor-packages/pkg/actions/group.py", line 80, in install
    if (cur_attrs["gid"] != self.attrs["gid"]):
KeyError: 'gid'


pkg: This is an internal error in pkg(5) version a1fb8dcc1a5e.  Please log a
Service Request about this issue including the information above and this
message.
```

When checking the /etc/group file, I have observed that both the user wazuh and ossec exist. When you remove them, the installation is successful.

```
root@sossp534:~# pkg install -g wazuh-agent_v4.2.5-sol11-sparc.p5p wazuh-agent
           Packages to install:  1
            Services to change:  1
       Create boot environment: No
Create backup boot environment: No

DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                1/1         86/86      5.4/5.4    0B/s

PHASE                                          ITEMS
Installing new actions                       131/131
Updating package state database                 Done 
Updating package cache                           0/0 
Updating image state                            Done 
Creating fast lookup database                   Done 
Updating package cache                           2/2 
root@sossp534:~# 
```

Regards, Raúl.

**Comment by vikman90** [comment]
This problem is known and we do not plan to fix that. In addition, the documentation states that we need to remove the user manually: https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-solaris.html.
