### ISSUE TITLE
Investigate the modification of the Node Wrapper provided in the Dashboard package

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1447]
We need to validate if we can modify the configuration path used by Wazuh Dashboard, changing it from install_path/config to /etc/wazuh-dashboard/

```
wazuh-dashboard@wazuh-dashboard:~$ cat /usr/share/wazuh-dashboard/bin/opensearch-dashboards
#!/bin/sh
SCRIPT=$0

# SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
while [ -h "$SCRIPT" ] ; do
  ls=$(ls -ld "$SCRIPT")
  # Drop everything prior to ->
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=$(dirname "$SCRIPT")/"$link"
  fi
done

DIR="$(dirname "${SCRIPT}")/.."
CONFIG_DIR=${OSD_PATH_CONF:-"$DIR/config"}

if [ -x "${DIR}/node/bin/node" ]; then
  NODE="${DIR}/node/bin/node"
else
  NODE="$(which node)"
fi

if [ ! -x "$NODE" ]; then
  echo "unable to find usable node.js executable."
  exit 1
fi

if [ -f "${CONFIG_DIR}/node.options" ]; then
  OSD_NODE_OPTS="$(grep -v ^# < ${CONFIG_DIR}/node.options | xargs)"
fi

NODE_OPTIONS="--no-warnings --max-http-header-size=65536 $OSD_NODE_OPTS $NODE_OPTIONS" NODE_ENV=production exec "${NODE}" "${DIR}/src/cli/dist" ${@}

```

**Comment by c-bordon** [comment]
I made the changes to the opensearch-dashboards scripts by modifying the config path, but when running the scripts it still takes the old path, this is probably in these files somehow:

```
[root@centos7-1 wazuh-dashboard]# /usr/share/wazuh-dashboard/bin/opensearch-dashboards
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at readYaml (/usr/share/wazuh-dashboard/node_modules/@osd/apm-config-loader/target/utils/read_config.js:38:52)
    at Object.exports.getConfigFromFiles (/usr/share/wazuh-dashboard/node_modules/@osd/apm-config-loader/target/utils/read_config.js:63:22)
    at exports.loadConfiguration (/usr/share/wazuh-dashboard/node_modules/@osd/apm-config-loader/target/config_loader.js:44:38)
    at module.exports (/usr/share/wazuh-dashboard/src/apm.js:60:15)
    at Object.<anonymous> (/usr/share/wazuh-dashboard/src/cli/dist.js:34:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

```

**Comment by teddytpc1** [comment]
@c-bordon I have been testing the `node.options` and the `/usr/share/wazuh-dashboard/bin/opensearch-dashboards` script is looking for the `node.options` file in `/usr/share/wazuh-dashboard/config` but the file is located in `/etc/wazuh-dashboard` when a package installation is performed. We have 2 options: 
- Modify the script to set `CONFIG_DIR=/etc/wazuh-dashboard`
- Modify the package to place the `node.options` file under `/usr/share/wazuh-dashboard/config` directory.
