### ISSUE TITLE
Task manager show old wazuh logo after windows wpk upgrade

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1474]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 | Agent | WPK Upgrade | Windows Server 2016 |

Testing the [v4.3.0-rc6 windows wpk package](https://github.com/wazuh/wazuh/issues/13159#issuecomment-1104392878), I have seen that the wazuh icon is not updated in the processes shown by the task manager, keeping the old logo

- Wazuh process icon in task manager details tab does not change after upgrade to v4.3.0
- Wazuh 4.3.0 windows package show the correct icon in task manager details tab
- Direct upgrade from 4.2.6 to 4.3.0, change the icon
- During the wpk upgrade its possible to see how the wazuh process (processes tab) disappear, but the wazuh process persist in the  details tab, this seems to be because the disappearing process belongs to the UI, but the main wazuh process persists internally
- Running the UI again, the wazuh process (UI and main) keep the old logo in processes and details tab
- System restart does not change icon, closing and opening task manager does not change icon

Task manager icons:

![image](https://user-images.githubusercontent.com/14913942/164313966-ba41bf37-dff3-4323-8aaa-cad3e93298b3.png)
![image](https://user-images.githubusercontent.com/14913942/164314006-0b8317fb-0d53-4044-bda8-dcfeb637d9df.png)

**Comment by rauldpm** [comment]
### Update report

---

- Installed v4.2.6, connected to 4.3.0 manager
- Task manager and windows explorer closed
- Upgraded via wpk
- All icons upgraded

---

- Installed v4.2.6, connected to 4.3.0 manager
- Opened task manager and ossec-agent directory
- Upgraded via wpk, agent_upgrade show error, upgrade is done and agent in upgraded to 4.3.0
- UI closed, wazuh-agent.exe process persists, wazuh icons show old logo
- Opened wazuh UI, new icon is displayed in UI
- wazuh-agent.exe properties display new logo
- Restarted system, windows show new logo, task manager keep displaying old logo

<details><summary>agent_upgrade error</summary>

```
[root@centos7 vagrant]# /var/ossec/bin/agent_upgrade -a 001 -f /home/vagrant/wazuh_agent_v4.3.0_windows.wpk -x upgrade.bat

Upgrading...
Error executing API request locally: time data '0' does not match format '%Y/%m/%d %H:%M:%S'
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 242, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/decorators.py", line 420, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/agent.py", line 1057, in get_upgrade_result
    task_results.append(core_upgrade_agents(agents_chunk=agents_chunk, get_result=True))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/agent.py", line 1101, in core_upgrade_agents
    [agent_info.update((k, datetime.strptime(v, "%Y/%m/%d %H:%M:%S").strftime(date_format))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/agent.py", line 1101, in <listcomp>
    [agent_info.update((k, datetime.strptime(v, "%Y/%m/%d %H:%M:%S").strftime(date_format))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/agent.py", line 1101, in <genexpr>
    [agent_info.update((k, datetime.strptime(v, "%Y/%m/%d %H:%M:%S").strftime(date_format))
  File "/var/ossec/framework/python/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/var/ossec/framework/python/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '0' does not match format '%Y/%m/%d %H:%M:%S'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 287, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
ValueError: time data '0' does not match format '%Y/%m/%d %H:%M:%S'
Internal error: 
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 220, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 197, in main
    check_status(affected_agents=result.affected_items, result_dict=agents_versions,
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 154, in check_status
    task_results = send_command(function=get_upgrade_result, command={'agent_list': list(affected_agents)},
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 115, in send_command
    return raise_if_exc(pool.submit(run, dapi.distribute_function()).result())
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/util.py", line 293, in raise_if_exc
    _create_problem(obj)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/util.py", line 263, in _create_problem
    raise ProblemException(status=500 if not code else code, type=exc.type, title=exc.title, detail=exc.message,
connexion.exceptions.ProblemException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 227, in <module>
    if args.debug:
AttributeError: 'Namespace' object has no attribute 'debug'
```

</details>

<details><summary>Video</summary>

![image](https://user-images.githubusercontent.com/14913942/164514400-fe357a80-cf21-45cf-ba77-f8977b1fdbc2.png)

https://user-images.githubusercontent.com/14913942/164515644-32f1d493-48d8-4c15-b938-dea83dbc6a49.mp4

https://user-images.githubusercontent.com/14913942/164515650-8f389b67-46cf-4544-9a01-f075d8e7895c.mp4



</details>

---

**Comment by rauldpm** [comment]
### Update report

- Installing 4.3.0 package with powershell console, application icon show old logo(tasks bar)
- 
![image](https://user-images.githubusercontent.com/14913942/164554098-96381865-a0a4-4743-a93d-d60032be75ed.png)

**Comment by rauldpm** [comment]
### Update report - Testing msi upgrade in Windows Server 2019

<details><summary>Powershell elevated upgrade as vagrant user and GUI upgrade, closed agent :green_circle: </summary>

```
- Install 4.2.6
- Open UI and start agent
- Wait to agent being mark as active in manager
- Stop agent and close UI
- Upgrade to 4.3.0. Success
```

- All icon updated (task manager was opened and needed to be closed and opened again to show new icon)

</details>

<details><summary>Powershell elevated upgrade as vagrant user, running and opened UI agent :green_circle:</summary>

```
- Install 4.2.6
- Open UI and start agent
- Wait to agent being mark as active in manager
- Keep agent running and opened UI
- Upgrade to 4.3.0. Success
```

- All icon updated (task manager was opened and needed to be closed and opened again to show new icon)

</details>

<details><summary>GUI upgrade as vagrant user, running and opened UI agent :red_circle:</summary>

```
- Install 4.2.6
- Open UI and start agent
- Wait to agent being mark as active in manager
- Keep agent running and opened UI
- Upgrade to 4.3.0. Failed
```

- Dialog box appeared about unable to automatically close all requested applications
- Dialog box appeared with error code 2349
- Agent rollback to 4.2.6
 
![win1](https://user-images.githubusercontent.com/14913942/164730576-92fde58d-25eb-4e61-9b35-a1066cd284c8.png)
![win11](https://user-images.githubusercontent.com/14913942/164730579-f4220c86-b1c7-4cce-b4b1-ac03b45880eb.png)


</details>

<details><summary>GUI upgrade as Administrator user, running and opened UI agent :green_circle:</summary>

```
- Install 4.2.6
- Open UI and start agent
- Wait to agent being mark as active in manager
- Keep agent running and opened UI
- Upgrade to 4.3.0. Success
```

</details>

---

- If manager has already registered the uninstalled agent, agent GUI shows an agent state contradiction

<details><summary>Steps</summary>

```
- Connect agent to manager
- Uninstall agent, manager keep the agent registered
- Install agent 4.2.6
- Start UI, introduce ip, save it
- Manage -> Start
- Dialog box informing about agent running must appear
- UI must show `Status: Require import of authentication key, Not Running`
- Manager -> Status show agent as running
- Refresh button does not change status
```

![image](https://user-images.githubusercontent.com/14913942/164731229-3a4fc126-88b0-4cf2-b858-b3a2867a30da.png)


</details>

**Comment by rauldpm** [comment]
### Update report WPK - Windows Server 2016

<details><summary>Upgrade 4.2.6-4.3.0 wpk :red_circle:</summary>

```
- Install 4.2.6 agent
- Start UI, save IP, start agent
- Wait agent to be active in manager agent_control
- Run wpk upgrade
  -  /var/ossec/bin/agent_upgrade -a 008 -f /home/wazuh-user/wazuh_agent_v4.3.0_windows.wpk -x upgrade.bat
- Upgrade success
- Control panel - Uninstall section show new logo
- win32ui.exe show new logo (properties too) 
- wazuh-agent.exe show old logo (properties too) :red_circle: 
- Restarting task manager show new logo
```

![image](https://user-images.githubusercontent.com/14913942/164737268-294582a4-8e45-4e56-a736-f13642386688.png)


</details>

**Comment by rauldpm** [comment]
### Update report

- Previous versions of windows 8 included use a different parameter for ie4uinit.exe 
  - Windows 8 and earlier: `ie4uinit.exe -ClearIconCache`
  - Windows 10  and later: `ie4uinit.exe -show`
