### ISSUE TITLE
 Wazuh indexer installation fails on Ubuntu 14

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1701]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.4 | Wazuh indexer | Install | Ubuntu 14 |

Following the Wazuh indexer installation documentation, I have found an error when installing the package:

<details><summary>Install output error</summary>

```
root@ubuntu14:/home/vagrant# cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@ubuntu14:/home/vagrant#
root@ubuntu14:/home/vagrant# apt -y install wazuh-indexer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 365 MB of archives.
After this operation, 639 MB of additional disk space will be used.
Get:1 https://packages.wazuh.com/4.x/apt/ stable/main wazuh-indexer amd64 4.3.4-1 [365 MB]
Fetched 365 MB in 15s (23.3 MB/s)                                              
Selecting previously unselected package wazuh-indexer.
(Reading database ... 63238 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.3.4-1_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.3.4-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up wazuh-indexer (4.3.4-1) ...
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:65)
	at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.jav
a:48)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean
(PlatformMBeanProviderImpl.java:281)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(Platfor
mMBeanProviderImpl.java:198)
	at java.management/java.lang.management.ManagementFactory.lambda$getPlatformMBeanServer$0(Manage
mentFactory.java:487)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1766)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFacto
ry.java:488)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:637)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:302)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:20
9)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:243)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:219)
	at org.opensearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:275)
	at org.opensearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:119
)
	at org.opensearch.cli.CommandLoggingConfigurator.configureLoggingWithoutConfig(CommandLoggingCon
figurator.java:53)
	at org.opensearch.cli.Command.main(Command.java:98)
	at org.opensearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:56)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:
64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorIm
pl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:61)
	... 26 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:77)
	at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:163)
	... 31 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 1
	at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.initSubsystem(CgroupV2Subsystem.ja
va:71)
	at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.<clinit>(CgroupV2Subsystem.java:42
)
	... 33 more
dpkg: error processing package wazuh-indexer (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...
Errors were encountered while processing:
 wazuh-indexer
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@ubuntu14:/home/vagrant#
```

</details>

- It is possible that it is related to initializing the service after installation `Caused by: java.lang.ExceptionInInitializerError`
- Reviewing the system, I have seen that although error, the following directories exist

<details><summary>/etc/wazuh-indexer</summary>

```
root@ubuntu14:/home/vagrant# ls -l /etc/wazuh-indexer
total 32
-rw-rw---- 1 wazuh-indexer wazuh-indexer  2560 Jun 28 16:25 jvm.options
drwxr-x--- 2 wazuh-indexer wazuh-indexer  4096 Jun  3 12:07 jvm.options.d
-rw-rw---- 1 wazuh-indexer wazuh-indexer 11646 Jun  3 12:07 log4j2.properties
drwxr-x--- 2 wazuh-indexer wazuh-indexer  4096 Jun 28 16:25 opensearch-observability
drwxr-x--- 2 wazuh-indexer wazuh-indexer  4096 Jun 28 16:25 opensearch-reports-scheduler
-rw-rw---- 1 wazuh-indexer wazuh-indexer  2040 Jun  3 12:07 opensearch.yml
root@ubuntu14:/home/vagrant#
```

</details>

<details><summary>/usr/share/wazuh-indexer</summary>

```
root@ubuntu14:/home/vagrant# ls -l /usr/share/wazuh-indexer
total 248
drwxr-x---  2 wazuh-indexer wazuh-indexer   4096 Jun 28 16:25 bin
drwxr-x---  9 wazuh-indexer wazuh-indexer   4096 Jun 28 16:25 jdk
drwxr-x---  3 wazuh-indexer wazuh-indexer   4096 Jun 28 16:25 lib
-rw-r-----  1 wazuh-indexer wazuh-indexer  11358 Jan 14 03:35 LICENSE.txt
drwxr-x--- 20 wazuh-indexer wazuh-indexer   4096 Jun 28 16:25 modules
-rw-r-----  1 wazuh-indexer wazuh-indexer 215355 Jan 14 03:42 NOTICE.txt
drwxr-x---  6 wazuh-indexer wazuh-indexer   4096 Jun 28 16:25 performance-analyzer-rca
drwxr-x--- 14 wazuh-indexer wazuh-indexer   4096 Jun 28 16:25 plugins
root@ubuntu14:/home/vagrant#
```

</details>

- systemctl is not installed on the system
- service return error

```
root@ubuntu14:/home/vagrant# service wazuh-indexer status
status: invalid option: -p
Try `status --help' for more information.
root@ubuntu14:/home/vagrant#
```

Regards, Raúl.

**Comment by alberpilot** [comment]
Ubuntu 14 is not recommended for Indexer and dashboard, as specified in the documentation.
