### ISSUE TITLE
Wazuh dashboard show errors related to SSL

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2106]
## Description

The following log messages have been found in the [v4.4.0-rc1 AMI](https://github.com/wazuh/wazuh/issues/16148#issuecomment-1432987120) testing:

```
Feb 15 22:23:14 wazuh-server opensearch-dashboards[405]: {"type":"error","@timestamp":"2023-02-15T22:23:14Z","tags":["connection","client","error"],"pid":405,"level":"error","error":{"message":"139814486554496:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46\n","name":"Error","stack":"Error: 139814486554496:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46\n","code":"ERR_SSL_SSLV3_ALERT_CERTIFICATE_UNKNOWN"},"message":"139814486554496:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46\n"}
```

```
Feb 15 23:14:12 wazuh-server opensearch-dashboards[4795]: {"type":"error","@timestamp":"2023-02-15T23:14:12Z","tags":["connection","client","error"],"pid":4795,"level":"error","error":{"message":"140635959588736:error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share:../deps/openssl/openssl/ssl/statem/extensions_srvr.c:698:\n","name":"Error","stack":"Error: 140635959588736:error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share:../deps/openssl/openssl/ssl/statem/extensions_srvr.c:698:\n","code":"ERR_SSL_BAD_KEY_SHARE"},"message":"140635959588736:error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share:../deps/openssl/openssl/ssl/statem/extensions_srvr.c:698:\n"}
```

```
Feb 15 23:14:12 wazuh-server opensearch-dashboards[4795]: {"type":"error","@timestamp":"2023-02-15T23:14:12Z","tags":["connection","client","error"],"pid":4795,"level":"error","error":{"message":"140635959588736:error:142090C1:SSL routines:tls_early_post_process_client_hello:no shared cipher:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1781:\n","name":"Error","stack":"Error: 140635959588736:error:142090C1:SSL routines:tls_early_post_process_client_hello:no shared cipher:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1781:\n","code":"ERR_SSL_NO_SHARED_CIPHER"},"message":"140635959588736:error:142090C1:SSL routines:tls_early_post_process_client_hello:no shared cipher:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1781:\n"}
```

```
Feb 15 23:14:09 wazuh-server opensearch-dashboards[4795]: {"type":"error","@timestamp":"2023-02-15T23:14:09Z","tags":["connection","client","error"],"pid":4795,"level":"error","error":{"message":"140635959588736:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:\n","name":"Error","stack":"Error: 140635959588736:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:\n","code":"ERR_SSL_UNSUPPORTED_PROTOCOL"},"message":"140635959588736:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:\n"}
```

```
Feb 15 23:14:03 wazuh-server opensearch-dashboards[4795]: {"type":"error","@timestamp":"2023-02-15T23:14:03Z","tags":["connection","client","error"],"pid":4795,"level":"error","error":{"message":"140635959588736:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n","name":"Error","stack":"Error: 140635959588736:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n","code":"ERR_SSL_WRONG_VERSION_NUMBER"},"message":"140635959588736:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
```

```
Feb 15 17:31:58 wazuh-server opensearch-dashboards[4795]: {"type":"error","@timestamp":"2023-02-15T17:31:58Z","tags":[],"pid":4795,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/wazuh-dashboard/src/core/server/http/router/response_adapter.js:80:19)\n    at Router.handle (/usr/share/wazuh-dashboard/src/core/server/http/router/router.js:177:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/wazuh-dashboard/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"https://172.31.77.115/api/request","message":"Internal Server Error"}
```

```
Feb 15 17:31:58 wazuh-server opensearch-dashboards[4795]: {"type":"log","@timestamp":"2023-02-15T17:31:58Z","tags":["error","http"],"pid":4795,"message":"TypeError: message.includes is not a function\n    at ErrorResponse (/usr/share/wazuh-dashboard/plugins/wazuh/server/lib/error-response.ts:34:11)\n    at WazuhApiCtrl.makeRequest (/usr/share/wazuh-dashboard/plugins/wazuh/server/controllers/wazuh-api.ts:710:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Router.handle (/usr/share/wazuh-dashboard/src/core/server/http/router/router.js:163:44)\n    at handler (/usr/share/wazuh-dashboard/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:281:9)"}
```

Some of these messages are similar to others obtained previously but with a different format, probably due to a change on the part of OpenSearch. It is necessary to investigate these messages and establish the actions to be taken.

## Tasks

- [ ] Analyze each message obtained (OVA/AMI)
- [ ] Open an issue for each error and apply the necessary fix if necessary

## Validation

- [ ] The OVA/AMI are built without these error messages or it is validated that they can show them

**Comment by DFolchA** [comment]
## Update

After investigating, we found that this error is caused because the self-signed certificate used in the AMI is not trusted by the web browser trying to access the Wazuh dashboard.

To Fix these errors we would need to generate certificates signed by a trusted CA.

Resources:
https://www.elastic.co/blog/configuring-ssl-tls-and-https-to-secure-elasticsearch-kibana-beats-and-logstash?ultron=june-2019&blade=newsletter&hulk=email&mkt_tok=eyJpIjoiTlRBM1pqWTJPV0ppWldaaiIsInQiOiJiXC96b2JuZ0pUWEpCUDNzWDNlcmZualRmejM0blBVTk5tWFRsbTVubk9FXC9PNVIzTkIweWRGdXBzdXdmTjhPV0dyOFNPSzRuT3NZVXcwMDd6SFdnUFUxVnhoa29iWHZnRUJRbzd2Y1wveXE1MXUrVzlkdG96dnFcL1dabjNTczlUaXoifQ%253D%253D

**Comment by DFolchA** [comment]
## Update

We reproduced the issue with OVA and the unattended AIO installation.

Start testing if adding CA to the browser would avoid errors.

**Comment by DFolchA** [comment]
## Update 

Verify that each time the browser shows the message saying that the certificates are not trusted the dashboard generates this log error:


https://user-images.githubusercontent.com/19505384/221196239-02ab8b36-a929-4a0f-83a6-79c57dccba93.mp4
