### ISSUE TITLE
generate_wazuh_app bug

### ISSUE THREAD

**Issue by cx13283081880** [wazuh/wazuh-packages#2479]
when I used Wazuh packages generation guide-[Wazuh Kibana plugin](https://documentation.wazuh.com/current/development/packaging/generate-wazuh-kibana-app.html)
./generate_wazuh_app.sh -b v4.5.2-7.10.2 -s /wazuh-app -r 1
I can't finish it,
error /tmp/source/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /tmp/source/node_modules/puppeteer
Output:
ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/tmp/source/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/tmp/source/node_modules/puppeteer/install.js:66:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
after I changed the npm'source ,i got
error /tmp/source/node_modules/chromedriver: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /tmp/source/node_modules/chromedriver
Output:
Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
Saving to file: /tmp/87.0.4280.20/chromedriver/chromedriver_linux64.zip
ChromeDriver installation failed Error: Error with http(s) request: Error: read ECONNRESET

I want to know what‘s the difference between wauzh-packages/stack/dashboard/rpm/build_package.sh and this.
If I want to build wazuh-dashboard package,which way should i choose?

**Comment by jnasselle** [comment]
Hi @cx13283081880 ,

I was not able to reproduce your error after executing the guide several times. After reading the error, it seems to be a connectivity issue. Did you tried to execute it again?

About the question of the difference between this script and wauzh-packages/stack/dashboard/rpm/build_package.sh, is that this last one depends on the generation of the first one (Wazuh App zip file) by using the `--app-url`

**Comment by jnasselle** [comment]
Closing this issue due to inactivity, feel free to open an issue if necessary.
