### ISSUE TITLE
Logtest socket is missing in OVA

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-packages#650]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.1.1-40110 | OVA | Import | CentOS7 |

Running `/var/ossec/bin/wazuh-logtest` in a newly imported OVA will fail after providing a log.
Similarly the API call:
```
curl -k -X PUT "https://localhost:55000/logtest" -H  "Authorization: Bearer $(curl -uwazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")" -H  "Content-Type: application/json" -d '{"log_format":"syslog","location":"agent007","event":"test"}'
```
Will result in:
```
{"title": "Wazuh Internal Error", "detail": "Wazuh Internal Error", "remediation": "Please, check `WAZUH_HOME/logs/ossec.log`, `WAZUH_HOME/logs/cluster.log` and `WAZUH_HOME/logs/api.log` to get more information about the error", "dapi_errors": {"node01": {"error": "Unable to connect with socket: [Errno 2] No such file or directory", "logfile": "WAZUH_HOME/logs/api.log"}}, "error": 1000}
```

The `/var/ossec/logs/api.log` then contains the following error:
```
2021/02/26 20:57:38 ERROR: Error executing API request locally: Error 1013 - Unable to connect with socket: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/wazuh_socket.py", line 27, in _connect
    self.s.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 491, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 224, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/rbac/decorators.py", line 406, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/logtest.py", line 40, in run_logtest
    response = send_logtest_msg(command='log_processing', parameters=local_vars)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/logtest.py", line 27, in send_logtest_msg
    logtest_socket = OssecSocketJSON(LOGTEST_SOCKET)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/wazuh_socket.py", line 60, in __init__
    OssecSocket.__init__(self, path)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/wazuh_socket.py", line 22, in __init__
    self._connect()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/wazuh_socket.py", line 29, in _connect
    raise WazuhException(1013, str(e))
wazuh.core.exception.WazuhException: Error 1013 - Unable to connect with socket: [Errno 2] No such file or directory
```
Tracing that error the missing socket is `/var/ossec/queue/ossec/logtest`. 

Using the [unnatended installation script](https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/unattended-installation.html) on a CentOS 7 the socket file is observed and both `wazuh-logtest` and the API call work as expected.

The error is also observed in the OVA for 4.1.0.

An initial analysis did not provide clues on the cause or why it would be different from an installation an unnatended installation.

**Comment by jnasselle** [comment]
Hi team!

I figured out that the problem is the `enable` value of `rule_test` section in `ossec.conf`. Currently is set to `no`, but it should be `yes`.

Regards,
Nico
